### ISSUE TITLE
Train on multi GPU, custom dataset.

### ISSUE THREAD

**Issue by jasuriy** [Harxis/G2Face#3]
@Harxis hi 
I have seen your job and it is fascinating. really interesting. 
I was trying to train this model with my server and getting this error. I tried with my pc with a single GPU and it worked fine but with server with multi gpu, throwing error. could you please have a look at it. thank you in advance:

G2Face_docker# python train.py --ffhq_path k_real_10000_fid_test --celebahq_path k_real_3099_fid_test 
[2024-11-28 05:41:16,316][INFO] --------------------------------------------------setting--------------------------------------------------
[2024-11-28 05:41:16,316][INFO] resume: False
[2024-11-28 05:41:16,316][INFO] seed: 2024
[2024-11-28 05:41:16,316][INFO] resume_weights: 
[2024-11-28 05:41:16,316][INFO] work_path: ./run
[2024-11-28 05:41:16,317][INFO] distributed: False
[2024-11-28 05:41:16,317][INFO] local_rank: -1
[2024-11-28 05:41:16,317][INFO] device: cuda
[2024-11-28 05:41:16,317][INFO] celebahq_path: k_real_3099_fid_test
[2024-11-28 05:41:16,317][INFO] ffhq_path: k_real_10000_fid_test
[2024-11-28 05:41:16,317][INFO] image_size: 512
[2024-11-28 05:41:16,317][INFO] lr: 0.001
[2024-11-28 05:41:16,317][INFO] batch_size: 8
[2024-11-28 05:41:16,317][INFO] num_iter: 100000
[2024-11-28 05:41:16,317][INFO] d_reg_every: 16
[2024-11-28 05:41:16,317][INFO] augment: False
[2024-11-28 05:41:16,317][INFO] augment_p: 0
[2024-11-28 05:41:16,317][INFO] ada_target: 0.6
[2024-11-28 05:41:16,317][INFO] ada_length: 500000
[2024-11-28 05:41:16,317][INFO] ada_every: 256
[2024-11-28 05:41:16,317][INFO] latent_dim: 659
[2024-11-28 05:41:16,317][INFO] style_dim: 512
[2024-11-28 05:41:16,317][INFO] n_mlp: 4
[2024-11-28 05:41:16,317][INFO] l1_coef: 1
[2024-11-28 05:41:16,317][INFO] lpips_coef: 1
[2024-11-28 05:41:16,317][INFO] id_coef: 1
[2024-11-28 05:41:16,317][INFO] vert_coef: 1
[2024-11-28 05:41:16,317][INFO] tex_coef: 1
[2024-11-28 05:41:16,317][INFO] col_coef: 1
[2024-11-28 05:41:16,317][INFO] lm_coef: 0.01
[2024-11-28 05:41:16,317][INFO] hiding_coef: 10
[2024-11-28 05:41:16,317][INFO] diversity_coef: 1
[2024-11-28 05:41:16,317][INFO] gp_coef: 5
[2024-11-28 05:41:16,317][INFO] isTrain: False
[2024-11-28 05:41:16,317][INFO] phase: test
[2024-11-28 05:41:16,317][INFO] net_recon: resnet50
[2024-11-28 05:41:16,317][INFO] init_path: weights/epoch_20.pth
[2024-11-28 05:41:16,317][INFO] use_last_fc: False
[2024-11-28 05:41:16,317][INFO] bfm_folder: model/d3dfr/BFM
[2024-11-28 05:41:16,317][INFO] bfm_model: BFM_model_front.mat
[2024-11-28 05:41:16,317][INFO] checkpoints_dir: ./weights
[2024-11-28 05:41:16,317][INFO] name: 
[2024-11-28 05:41:16,317][INFO] focal: 1015.0
[2024-11-28 05:41:16,317][INFO] center: 112.0
[2024-11-28 05:41:16,318][INFO] camera_d: 10.0
[2024-11-28 05:41:16,318][INFO] z_near: 5.0
[2024-11-28 05:41:16,318][INFO] z_far: 15.0
[2024-11-28 05:41:16,318][INFO] use_opengl: True
[2024-11-28 05:41:16,318][INFO] -----------------------------------------------------------------------------------------------------------
weights/epoch_20.pth
loading the model from ./weights/epoch_20.pth
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /usr/local/lib/python3.8/dist-packages/lpips/weights/v0.1/vgg.pth
Traceback (most recent call last):
  File "train.py", line 583, in <module>
    train(opt, logger, work_path)
  File "train.py", line 169, in train
    train_loader, test_loader = setup_data(opt)
ValueError: too many values to unpack (expected 2)
root@fvt:/G2Face_docker# python train.py --ffhq_path k_real_10000_fid_test --celebahq_path k_real_3099_fid_test 
[2024-11-28 05:44:56,327][INFO] --------------------------------------------------setting--------------------------------------------------
[2024-11-28 05:44:56,327][INFO] resume: False
[2024-11-28 05:44:56,327][INFO] seed: 2024
[2024-11-28 05:44:56,327][INFO] resume_weights: 
[2024-11-28 05:44:56,327][INFO] work_path: ./run
[2024-11-28 05:44:56,327][INFO] distributed: False
[2024-11-28 05:44:56,327][INFO] local_rank: -1
[2024-11-28 05:44:56,327][INFO] device: cuda
[2024-11-28 05:44:56,327][INFO] celebahq_path: k_real_3099_fid_test
[2024-11-28 05:44:56,327][INFO] ffhq_path: k_real_10000_fid_test
[2024-11-28 05:44:56,327][INFO] image_size: 512
[2024-11-28 05:44:56,327][INFO] lr: 0.001
[2024-11-28 05:44:56,327][INFO] batch_size: 8
[2024-11-28 05:44:56,327][INFO] num_iter: 100000
[2024-11-28 05:44:56,327][INFO] d_reg_every: 16
[2024-11-28 05:44:56,327][INFO] augment: False
[2024-11-28 05:44:56,328][INFO] augment_p: 0
[2024-11-28 05:44:56,328][INFO] ada_target: 0.6
[2024-11-28 05:44:56,328][INFO] ada_length: 500000
[2024-11-28 05:44:56,328][INFO] ada_every: 256
[2024-11-28 05:44:56,328][INFO] latent_dim: 659
[2024-11-28 05:44:56,328][INFO] style_dim: 512
[2024-11-28 05:44:56,328][INFO] n_mlp: 4
[2024-11-28 05:44:56,328][INFO] l1_coef: 1
[2024-11-28 05:44:56,328][INFO] lpips_coef: 1
[2024-11-28 05:44:56,328][INFO] id_coef: 1
[2024-11-28 05:44:56,328][INFO] vert_coef: 1
[2024-11-28 05:44:56,328][INFO] tex_coef: 1
[2024-11-28 05:44:56,328][INFO] col_coef: 1
[2024-11-28 05:44:56,328][INFO] lm_coef: 0.01
[2024-11-28 05:44:56,328][INFO] hiding_coef: 10
[2024-11-28 05:44:56,328][INFO] diversity_coef: 1
[2024-11-28 05:44:56,328][INFO] gp_coef: 5
[2024-11-28 05:44:56,328][INFO] isTrain: False
[2024-11-28 05:44:56,328][INFO] phase: test
[2024-11-28 05:44:56,328][INFO] net_recon: resnet50
[2024-11-28 05:44:56,328][INFO] init_path: weights/epoch_20.pth
[2024-11-28 05:44:56,328][INFO] use_last_fc: False
[2024-11-28 05:44:56,328][INFO] bfm_folder: model/d3dfr/BFM
[2024-11-28 05:44:56,328][INFO] bfm_model: BFM_model_front.mat
[2024-11-28 05:44:56,328][INFO] checkpoints_dir: ./weights
[2024-11-28 05:44:56,328][INFO] name: 
[2024-11-28 05:44:56,328][INFO] focal: 1015.0
[2024-11-28 05:44:56,328][INFO] center: 112.0
[2024-11-28 05:44:56,328][INFO] camera_d: 10.0
[2024-11-28 05:44:56,328][INFO] z_near: 5.0
[2024-11-28 05:44:56,328][INFO] z_far: 15.0
[2024-11-28 05:44:56,328][INFO] use_opengl: True
[2024-11-28 05:44:56,328][INFO] -----------------------------------------------------------------------------------------------------------
weights/epoch_20.pth
loading the model from ./weights/epoch_20.pth
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /usr/local/lib/python3.8/dist-packages/lpips/weights/v0.1/vgg.pth
Traceback (most recent call last):
  File "train.py", line 583, in <module>
    train(opt, logger, work_path)
  File "train.py", line 262, in train
    anonymous_image = anonymous_net(ori_image, latent_control_anonymous, binary_hiding)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/G2Face_docker/model/style/style_adaptive_mask.py", line 577, in forward
    concate_feature = torch.cat([out, original_image_feature], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 2 for tensor number 1 in the list.

**Comment by Harxis** [comment]
It looks like there is a problem with the loading of the dataset, please make sure your data is read correctly. To train with multiple GPUs, you need to use torch.distributed.launch.

**Comment by jasuriy** [comment]
Thank you for your reply. The issue is resolved. it was my mistake in
options.py and train.py.

**Comment by jasuriy** [comment]
Hi Mr. Yan
I am sorry if I am bothering you with silly questions. But please
understand I am just a student in this field.
My question is: I tried to train the G2Face with my custom dataset. But as
my dataset is so small (10k images) the results are not that good. So I
wanted to do transfer learning with pretrained weights of the ffhq dataset.
Is it available in the Google drive link you attached in the git repository
page? I saw some pretrained weights in there but couldn't distinguish them.

Sincerely
Jasurbek

**Comment by Harxis** [comment]
Hello, the pretrained weight is ``weights/G2Face.pth`` in the google drive.
